# Generated by Django 5.1.2 on 2024-10-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.dealer')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycles.motorcycle')),
            ],
        ),
    ]
