# Generated by Django 5.1.2 on 2024-10-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
        ('motorcycles', '0002_alter_brand_country_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='motorcycledealer',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='motorcycledealer',
            unique_together={('motorcycle', 'dealer')},
        ),
    ]
